### ISSUE TITLE
Animated GIF doesn't work

### ISSUE THREAD

**Issue by phormio** [chunkhang/simple-totp#1]
The animated GIF in the "Demonstration" section of the README doesn't work for me. I see a partial image, with no animation. See screenshot:

![Screenshot_2024-10-06_17-30-16](https://github.com/user-attachments/assets/d622c997-5b39-4eb7-8725-1e2301b608d0)

I have viewed the README in 2 different browsers.

**Comment by chunkhang** [comment]
Thanks, it should be fixed now.
